### ISSUE TITLE
Grammar for constraining choices

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-grammar#17]
Do we have a grammar for constraining choices?
Example:

Element:		Reason
Value:   string or CodeableConcept or ref(Condition)

EntryElement:	GoalPursuit
0..1                  Reason _choices are_ ref(Condition)

**Comment by cmoesel** [comment]
This can be done as below:

```
Element:	Reason
Value: string or CodeableConcept or ref(Condition)

EntryElement:	GoalPursuit
0..1 Reason value is type ref(Condition)
```

**Comment by markkramerus** [comment]
There are two limitations, however:
1)  Constraining from 3 or more to 2 more choices:
EntryElement:	GoalPursuit
0..1 Reason value is type ref(Condition) or string  <<< this isn't the greatest example since it is a primitive but the point is, we don't have the ability to narrow to a choice of N to a choice of M where M<N but M>1

2) Constraining to a primitive value:
0..1 Reason value is string

**Comment by cmoesel** [comment]
It's good to note those here, but they are already represented by two other more specific bug reports:

1. _1..1 Value is type ref(A) or ref(B) not expanded correctly_ (standardhealth/shr-expand#17)
2. _Cannot constrain value choice to primitive (from a field)_ (standardhealth/shr-grammar#27)

Is it ok to close this since it answers the original question and the specific variants on it are already reported elsewhere?

**Comment by markkramerus** [comment]
Closing again in view of duplicate issues, per Chris' comment.
