### ISSUE TITLE
Quantity with units from value set

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-grammar#24]
Currently, we support this type of unit constraint on a Quantity:
```
Quantity with units UCUM#kg "kg"
```

Some of the published FHIR vital signs profiles, however, bind the quantity unit to a value set.  To support this, the grammar will need to be extended to allow things such as:
```
Quantity with units from http://hl7.org/fhir/ValueSet/ucum-bodyweight
```

**Comment by markkramerus** [comment]
I think we have to do it. Separately, yesterday, I ran into a case where there was a choice of allowed units, either L/min or mL/min. Without the option of a value set for units, we can't do that.  It does bring up the question of special syntax. I think we can already do everything we want with "regular" syntax:
Quantity.Units from myUnitsVS 
or
Quantity.Units is UCUM#L/min
Should we just remove the special units syntax, instead of adding MORE special syntax???
Sometimes syntactic sugar is just more to remember.

**Comment by markkramerus** [comment]
Supported now:
Example:
Group:             Age
Parent:            Quantity
Concept:           MTH#C0001779
Description:       "How long someone has been alive, or something has existed."
                   Units from http://hl7.org/fhir/ValueSet/age-units (extensible)
